server:
  port: 8080
  session:
    timeout: 10800

multipart:
  max-file-size: 50MB
  max-request-size: 50MB

spring:
  application:
    name: core-service
  data:
    rest:
      basePath: /api
    mongodb:
      host: mongodb
      port: 27017
      database: marble
  thymeleaf:
    cache: false 
    
# Discovery Server Access
#  1. Define URL of registration server (defaultZone)
#  2. Reduce lease-renewal time so processes register more quickly
eureka:
  instance:
     leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
     leaseExpirationDurationInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://registry:1111/eureka/

access:
  admin:
    username: '@access.admin.username@'
    password: '@access.admin.password@'
  oper:
    username: '@access.oper.username@'
    password: '@access.oper.password@'
  guest:
    username: '@access.guest.username@'
    password: '@access.guest.password@'
