server:
  port: 9112
  session:
    timeout: 10800

multipart:
  max-file-size: 50MB
  max-request-size: 50MB

spring:
  application:
    name: processor-stanford
  data:
    mongodb:
      host: localhost
      port: 27017
      database: marble-processor-stanford
  freemarker:
    enabled: false        
  thymeleaf:
    enable: false 
  jersey:
    application-path: /api
    
# Discovery Server Access
#  1. Define URL of registration server (defaultZone)
#  2. Reduce lease-renewal time so processes register more quickly
eureka:
  instance:
     leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
     leaseExpirationDurationInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/